conformant = "Pass"
output = """
protocols_variance.py:21: error: Invariant type variable "T1" used in protocol where covariant one is expected  [misc]
protocols_variance.py:40: error: Invariant type variable "T3" used in protocol where contravariant one is expected  [misc]
protocols_variance.py:56: error: Invariant type variable "T1" used in protocol where contravariant one is expected  [misc]
protocols_variance.py:61: error: Covariant type variable "T1_co" used in protocol where contravariant one is expected  [misc]
protocols_variance.py:62: error: Cannot use a covariant type variable as a parameter  [misc]
protocols_variance.py:66: error: Invariant type variable "T1" used in protocol where covariant one is expected  [misc]
protocols_variance.py:71: error: Contravariant type variable "T1_contra" used in protocol where covariant one is expected  [misc]
protocols_variance.py:72: error: Cannot use a contravariant type variable as return type  [misc]
protocols_variance.py:104: error: Invariant type variable "T1" used in protocol where covariant one is expected  [misc]
"""
conformance_automated = "Fail"
errors_diff = """
Line 21: Unexpected errors ['protocols_variance.py:21: error: Invariant type variable "T1" used in protocol where covariant one is expected  [misc]']
Line 40: Unexpected errors ['protocols_variance.py:40: error: Invariant type variable "T3" used in protocol where contravariant one is expected  [misc]']
Line 56: Unexpected errors ['protocols_variance.py:56: error: Invariant type variable "T1" used in protocol where contravariant one is expected  [misc]']
Line 61: Unexpected errors ['protocols_variance.py:61: error: Covariant type variable "T1_co" used in protocol where contravariant one is expected  [misc]']
Line 62: Unexpected errors ['protocols_variance.py:62: error: Cannot use a covariant type variable as a parameter  [misc]']
Line 66: Unexpected errors ['protocols_variance.py:66: error: Invariant type variable "T1" used in protocol where covariant one is expected  [misc]']
Line 71: Unexpected errors ['protocols_variance.py:71: error: Contravariant type variable "T1_contra" used in protocol where covariant one is expected  [misc]']
Line 72: Unexpected errors ['protocols_variance.py:72: error: Cannot use a contravariant type variable as return type  [misc]']
Line 104: Unexpected errors ['protocols_variance.py:104: error: Invariant type variable "T1" used in protocol where covariant one is expected  [misc]']
"""
