conformant = "Pass"
output = """
specialtypes_none.py:21: error: Argument 1 to "func1" has incompatible type "type[None]"; expected "None"  [arg-type]
specialtypes_none.py:27: error: Incompatible types in assignment (expression has type "None", variable has type "Iterable[Any]")  [assignment]
specialtypes_none.py:41: error: Argument 1 to "func2" has incompatible type "None"; expected "type[None]"  [arg-type]
"""
conformance_automated = "Fail"
errors_diff = """
Line 21: Unexpected errors ['specialtypes_none.py:21: error: Argument 1 to "func1" has incompatible type "type[None]"; expected "None"  [arg-type]']
Line 27: Unexpected errors ['specialtypes_none.py:27: error: Incompatible types in assignment (expression has type "None", variable has type "Iterable[Any]")  [assignment]']
Line 41: Unexpected errors ['specialtypes_none.py:41: error: Argument 1 to "func2" has incompatible type "None"; expected "type[None]"  [arg-type]']
"""
