conformant = "Pass"
output = """
typeddicts_class_syntax.py:29: error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]
typeddicts_class_syntax.py:33: error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]
typeddicts_class_syntax.py:38: error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]
typeddicts_class_syntax.py:44: error: Unexpected keyword argument "metaclass" for "__init_subclass__" of "TypedDict"  [call-arg]
typeddicts_class_syntax.py:49: error: Unexpected keyword argument "other" for "__init_subclass__" of "TypedDict"  [call-arg]
"""
conformance_automated = "Fail"
errors_diff = """
Line 29: Unexpected errors ['typeddicts_class_syntax.py:29: error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]']
Line 33: Unexpected errors ['typeddicts_class_syntax.py:33: error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]']
Line 38: Unexpected errors ['typeddicts_class_syntax.py:38: error: Invalid statement in TypedDict definition; expected "field_name: field_type"  [misc]']
Line 44: Unexpected errors ['typeddicts_class_syntax.py:44: error: Unexpected keyword argument "metaclass" for "__init_subclass__" of "TypedDict"  [call-arg]']
Line 49: Unexpected errors ['typeddicts_class_syntax.py:49: error: Unexpected keyword argument "other" for "__init_subclass__" of "TypedDict"  [call-arg]']
"""
