conformant = "Pass"
output = """
dataclasses_transform_class.py:48:7 - error: A non-frozen class cannot inherit from a class that is frozen (reportGeneralTypeIssues)
dataclasses_transform_class.py:60:6 - error: Cannot assign member "id" for type "Customer1"
  "Customer1" is frozen
    Member "__set__" is unknown (reportAttributeAccessIssue)
dataclasses_transform_class.py:63:18 - error: Expected 0 positional arguments (reportCallIssue)
dataclasses_transform_class.py:69:6 - error: Operator "<" not supported for types "Customer1" and "Customer1" (reportOperatorIssue)
dataclasses_transform_class.py:79:18 - error: Expected 0 positional arguments (reportCallIssue)
dataclasses_transform_class.py:119:6 - error: Cannot assign member "id" for type "Customer3"
  "Customer3" is frozen
    Member "__set__" is unknown (reportAttributeAccessIssue)
"""
conformance_automated = "Fail"
errors_diff = """
Line 48: Unexpected errors ['dataclasses_transform_class.py:48:7 - error: A non-frozen class cannot inherit from a class that is frozen (reportGeneralTypeIssues)']
Line 60: Unexpected errors ['dataclasses_transform_class.py:60:6 - error: Cannot assign member "id" for type "Customer1"']
Line 63: Unexpected errors ['dataclasses_transform_class.py:63:18 - error: Expected 0 positional arguments (reportCallIssue)']
Line 69: Unexpected errors ['dataclasses_transform_class.py:69:6 - error: Operator "<" not supported for types "Customer1" and "Customer1" (reportOperatorIssue)']
Line 79: Unexpected errors ['dataclasses_transform_class.py:79:18 - error: Expected 0 positional arguments (reportCallIssue)']
Line 119: Unexpected errors ['dataclasses_transform_class.py:119:6 - error: Cannot assign member "id" for type "Customer3"']
"""
