conformant = "Pass"
output = """
generics_paramspec_basic.py:10:1 - error: ParamSpec must be assigned to a variable named "NotIt"
generics_paramspec_basic.py:15:18 - error: ParamSpec is not allowed in this context
generics_paramspec_basic.py:23:14 - error: ParamSpec is not allowed in this context
generics_paramspec_basic.py:23:20 - error: ParamSpec is not allowed in this context
generics_paramspec_basic.py:27:14 - error: "Concatenate" is not allowed in this context
generics_paramspec_basic.py:31:19 - error: Type "P@func3" cannot be assigned to type variable "_T@list"
  ParamSpec is not allowed in this context (reportInvalidTypeArguments)
generics_paramspec_basic.py:35:35 - error: ParamSpec is not allowed in this context
generics_paramspec_basic.py:39:18 - error: ParamSpec is not allowed in this context
generics_paramspec_basic.py:39:31 - error: ParamSpec is not allowed in this context
"""
conformance_automated = "Fail"
errors_diff = """
Line 10: Unexpected errors ['generics_paramspec_basic.py:10:1 - error: ParamSpec must be assigned to a variable named "NotIt"']
Line 15: Unexpected errors ['generics_paramspec_basic.py:15:18 - error: ParamSpec is not allowed in this context']
Line 23: Unexpected errors ['generics_paramspec_basic.py:23:14 - error: ParamSpec is not allowed in this context', 'generics_paramspec_basic.py:23:20 - error: ParamSpec is not allowed in this context']
Line 27: Unexpected errors ['generics_paramspec_basic.py:27:14 - error: "Concatenate" is not allowed in this context']
Line 31: Unexpected errors ['generics_paramspec_basic.py:31:19 - error: Type "P@func3" cannot be assigned to type variable "_T@list"']
Line 35: Unexpected errors ['generics_paramspec_basic.py:35:35 - error: ParamSpec is not allowed in this context']
Line 39: Unexpected errors ['generics_paramspec_basic.py:39:18 - error: ParamSpec is not allowed in this context', 'generics_paramspec_basic.py:39:31 - error: ParamSpec is not allowed in this context']
"""
