conformant = "Pass"
output = """
File "directives_assert_type.py", line 27, in func1: Union[int, str] [assert-type]
File "directives_assert_type.py", line 28, in func1: Any [assert-type]
File "directives_assert_type.py", line 31, in func1: Function assert_type expects 2 arg(s), got 0 [wrong-arg-count]
File "directives_assert_type.py", line 32, in func1: str [assert-type]
File "directives_assert_type.py", line 33, in func1: Function assert_type expects 2 arg(s), got 3 [wrong-arg-count]
"""
conformance_automated = "Fail"
errors_diff = """
Line 27: Unexpected errors ['File "directives_assert_type.py", line 27, in func1: Union[int, str] [assert-type]']
Line 28: Unexpected errors ['File "directives_assert_type.py", line 28, in func1: Any [assert-type]']
Line 31: Unexpected errors ['File "directives_assert_type.py", line 31, in func1: Function assert_type expects 2 arg(s), got 0 [wrong-arg-count]']
Line 32: Unexpected errors ['File "directives_assert_type.py", line 32, in func1: str [assert-type]']
Line 33: Unexpected errors ['File "directives_assert_type.py", line 33, in func1: Function assert_type expects 2 arg(s), got 3 [wrong-arg-count]']
"""
